services:
    _defaults:
        autowire: true
    DigipolisGent\Domainator9k\AppTypes\LaravelBundle\CacheClearer:
        tags:
            - {name: domainator.cacheclearer, for: DigipolisGent\Domainator9k\AppTypes\LaravelBundle\Entity\LaravelApplication}
